// AUTO-GENERATED by libs/routing/generate.mjs — do not edit manually
// Run: node libs/routing/generate.js

function applyQuery(path: string, query?: Record<string, string | number>): string {
  if (query) {
    const qs = new URLSearchParams(Object.entries(query).map(([k, v]) => [k, String(v)])).toString();
    return path + "?" + qs;
  }
  return path;
}

function resolvePath(path: string, params: Record<string, string | number>): string {
  return Object.entries(params).reduce((p, [segment, value]) => {
    return p.replace("[" + segment + "]", String(value));
  }, path);
}

export function root(query?: Record<string, string | number>) {
  return applyQuery("/", query);
}

export function admin(query?: Record<string, string | number>) {
  return applyQuery("/admin", query);
}

export function adminCompany(query?: Record<string, string | number>) {
  return applyQuery("/admin/company", query);
}

export function adminCompanyId(params: { id: string | number }, query?: Record<string, string | number>) {
  return applyQuery(resolvePath("/admin/company/[id]", params), query);
}

export function adminCompanyAddress(query?: Record<string, string | number>) {
  return applyQuery("/admin/company/address", query);
}

export function adminCompanyLocation(query?: Record<string, string | number>) {
  return applyQuery("/admin/company/location", query);
}

export function login(query?: Record<string, string | number>) {
  return applyQuery("/login", query);
}