// AUTO-GENERATED by libs/routing/generate.mjs — do not edit manually
// Run: node libs/routing/generate.js

export const APP_ROUTES = [
  "/",
  "/admin",
  "/admin/company",
  "/admin/company/[id]",
  "/admin/company/address",
  "/admin/company/location",
  "/login",
] as const;

export type AppPath = (typeof APP_ROUTES)[number];
