import { readdirSync, statSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { parseArgs } from "util";
import { generateHandlers } from "../utils/generateHandlers.mjs";

const ROOT = process.cwd();
const ROUTES_OUTPUT_FILE = "routes.generated.ts";
const HANDLERS_OUTPUT_FILE = "handlers.generated.ts";

const { values } = parseArgs({
  options: {
    app: { type: "string" },
  },
});

const __dirname = dirname(fileURLToPath(import.meta.url));

function collectRoutes(dir, basePath = "") {
  const routes = [];

  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry);
    const stat = statSync(fullPath);

    if (stat.isDirectory()) {
      // Skip parallel route slots (@header, @sidebar, etc.)
      if (entry.startsWith("@")) continue;

      // Route groups like (marketing) don't contribute a path segment
      const segment = /^\(.*\)$/.test(entry) ? "" : entry;
      const nextBase = segment ? `${basePath}/${segment}` : basePath;

      routes.push(...collectRoutes(fullPath, nextBase));
    } else if (/^page\.(tsx|ts|jsx|js)$/.test(entry)) {
      routes.push(basePath || "/");
    }
  }

  return routes;
}

function writeRoutes(routes) {
  const outputFile = join(__dirname, "../", ROUTES_OUTPUT_FILE);

  const lines = [
    "// AUTO-GENERATED by libs/routing/generate.mjs — do not edit manually",
    "// Run: node libs/routing/generate.js",
    "",
    `export const APP_ROUTES = ${JSON.stringify(routes, null, 2)} as const;`,
    "",
    "export type AppPath = (typeof APP_ROUTES)[number];",
    "",
  ];
  writeFileSync(outputFile, lines.join("\n"), "utf-8");
  console.log(
    `Generated ${routes.length} route(s) → libs/routing/routes.generated.ts`,
  );
  routes.forEach((r) => console.log(`  ${r}`));
}

function writeHandlers(routes) {
  const outputFile = join(__dirname, "../", HANDLERS_OUTPUT_FILE);
  writeFileSync(outputFile, generateHandlers(routes), "utf-8");
}

function start(path) {
  const APP_PATH = join(ROOT, path);
  const routes = [...new Set(collectRoutes(APP_PATH))].sort();

  writeRoutes(routes);
  writeHandlers(routes);
}

if (!values.app) {
  console.error(
    "Error: --app argument is required. Example: node generate.mjs --app=/src/app",
  );
  process.exit(1);
}

try {
  start(values.app);
} catch (err) {
  console.error("Error:", err.message);
  process.exit(1);
}
