import { test } from "node:test";
import assert from "node:assert/strict";
import { generateHandlers } from "./generateHandlers.mjs";

test("includes auto-generated header", () => {
  const result = generateHandlers(["/admin"]);
  assert.ok(result.includes("// AUTO-GENERATED by libs/routing/generate.mjs"));
  assert.ok(result.includes("// Run: node libs/routing/generate.js"));
});

test("includes applyQuery helper", () => {
  const result = generateHandlers(["/admin"]);
  assert.ok(result.includes("function applyQuery("));
});

test("includes resolvePath helper", () => {
  const result = generateHandlers(["/admin"]);
  assert.ok(result.includes("function resolvePath("));
});

test("includes all route handlers", () => {
  const result = generateHandlers(["/admin", "/admin/company/[id]"]);
  assert.ok(result.includes("export function admin("));
  assert.ok(result.includes("export function adminCompanyId("));
});

test("handlers call applyQuery and resolvePath instead of inlining logic", () => {
  const result = generateHandlers(["/admin/company/[id]"]);
  assert.ok(result.includes("applyQuery(resolvePath("));
  assert.ok(!result.includes("URLSearchParams", result.indexOf("export function")));
});
