function generateParams(path) {
  const matches = path.match(/\[([^\]]+)\]/g) ?? [];
  const extractedParams = matches.map((m) => m.slice(1, -1));
  if (!extractedParams.length) return "";
  return extractedParams.map((p) => `${p}: string | number`).join(", ");
}

function generateName(path) {
  const segments = path.split("/").filter(Boolean);

  if (!segments.length) return "root";

  return segments
    .map((segment, idx) => {
      const cleanSegment = segment.replace("[", "").replace("]", "");
      if (idx === 0) return cleanSegment;
      return cleanSegment.charAt(0).toUpperCase() + cleanSegment.slice(1);
    })
    .join("");
}

function generateHandler(path) {
  const name = generateName(path);
  const params = generateParams(path);

  if (params.length) {
    return [
      `export function ${name}(params: { ${params} }, query?: Record<string, string | number>) {`,
      `  return applyQuery(resolvePath("${path}", params), query);`,
      `}`,
    ].join("\n");
  }

  return [
    `export function ${name}(query?: Record<string, string | number>) {`,
    `  return applyQuery("${path}", query);`,
    `}`,
  ].join("\n");
}

function generateQueryHelper() {
  return [
    `function applyQuery(path: string, query?: Record<string, string | number>): string {`,
    `  if (query) {`,
    `    const qs = new URLSearchParams(Object.entries(query).map(([k, v]) => [k, String(v)])).toString();`,
    `    return path + "?" + qs;`,
    `  }`,
    `  return path;`,
    `}`,
  ].join("\n");
}

export function generatePathResolver() {
  return [
    `function resolvePath(path: string, params: Record<string, string | number>): string {`,
    `  return Object.entries(params).reduce((p, [segment, value]) => {`,
    `    return p.replace("[" + segment + "]", String(value));`,
    `  }, path);`,
    `}`,
  ].join("\n");
}

export function generateHandlers(routes) {
  const handlers = routes.map(generateHandler);

  return [
    "// AUTO-GENERATED by libs/routing/generate.mjs — do not edit manually",
    "// Run: node libs/routing/generate.js",
    "",
    generateQueryHelper(),
    "",
    generatePathResolver(),
    "",
    handlers.join("\n\n"),
  ].join("\n");
}
